### ISSUE TITLE
内存占用问题~

### ISSUE THREAD

**Issue by liuswong** [ryanlijianchang/AdPlayBanner#1]
将框架放入到项目中比没放之前占用的内存多了不少!有什么办法吗!

**Comment by liuswong** [comment]
在Memory里大概多了20M内存!

**Comment by ryanlijianchang** [comment]
很感谢你的issues，我重新看了一遍我的代码，并用leakcanary进行了一次内存泄漏检测，确实有点问题，现在已经修复了，**使用时大家可以使用最新的依赖，现在版本已经迭代了V0.3**。

其次回答下你的问题，我自己写了一个demo，并把AdPlayBanner嵌套的RecyclerView中，配合ViewPager和TabLayout使用，但是嵌套了AdPlayBanner之前和之后应用的内存大小差别不大，并没有你所说的多了20M内存之说，我想你的内存会增加大概是由于图片过大造成，如果可以的话，你可以把图片压缩到一定的比例再装载到AdPlayBanner中，而不是加载原图。附Demo地址：http://download.csdn.net/detail/ljcitworld/9923698。

如果还有问题的话，欢迎和我交流。
